name: practice_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  url_launcher: ^6.1.8
  image_picker: ^0.8.6+1
  fluttertoast: ^8.2.2
  geolocator: ^9.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2
  shimmer: ^2.0.0
  skeletons: ^0.0.3
  sensors_plus: ^2.0.1
  provider: ^6.0.5
  dotted_border: ^2.0.0+3
  appbar_animated: ^0.0.3
  animated_text_kit: ^4.2.2
  http: ^0.13.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.13
  share_plus: ^6.3.1
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^3.0.3
  device_info_plus: ^8.1.0
  google_fonts: ^4.0.3
  battery_plus: ^3.0.3
  flutter_local_notifications: ^13.0.0
  get_it: ^7.6.0
  dio: ^5.1.1
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.61.0
  video_player: ^2.6.1
  chewie: ^1.4.0
  google_maps_flutter: ^2.2.5
  cached_network_image: ^3.2.3
  flutter_screenutil: ^5.8.2
  flutter_bloc: ^8.1.3
  flutter_markdown: ^0.6.15
  auto_route: ^7.6.0
  injectable: ^2.1.2
  freezed_annotation: ^2.2.0
  permission_handler: ^10.4.2
  email_validator: '^2.1.16'
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  flutter_native_splash: ^2.2.17
  auto_route_generator: ^7.1.2
  freezed: ^2.3.5
  flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:
  image_path: assets/images/main_logo.png
  android: true
  ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splashscreen.png

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatar.png
    - assets/icons/star.gif
    - assets/images/placeholder.png
    - assets/images/login_cat.png
    - assets/images/signup_cat.png
    - assets/images/logout_cat.png
    - assets/images/splashscreen.png
    